<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_robot">

<!-- Here we define the model parameters -->

<!-- Geometry -->

<xacro:property name="base_link_length" value="0.05"/>
<xacro:property name="base_link_radius" value="0.2"/>

<xacro:property name="first_link_length" value="0.5"/>
<xacro:property name="first_link_radius" value="0.04"/>

<xacro:property name="second_link_length" value="1.0"/>
<xacro:property name="second_link_height" value="0.1"/>
<xacro:property name="second_link_width" value="0.1"/>

<!-- Joint Limits -->

<xacro:property name="limits_revolute_upper" value="3.14"/>
<xacro:property name="limits_revolute_lower" value="-3.14"/>
<xacro:property name="limits_revolute_velocity" value="3.14"/>
<xacro:property name="limits_revolute_effort" value="300"/>

<xacro:property name="limits_prismatic_upper" value="0.5"/>
<xacro:property name="limits_prismatic_lower" value="-0.5"/>
<xacro:property name="limits_prismatic_velocity" value="0.8"/>
<xacro:property name="limits_prismatic_effort" value="300"/>

<xacro:include filename="$(find robot_model3_pkg)/urdf/robot.gazebo"/>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
                
                <!-- origin - the reference frame of the visual element with respect to the reference frame of the link -->
                <!-- rpy - r: roll, p: pitch and y: yaw -->
                <!-- xyz - x, y, z offsets -->

                <origin xyz="0 0 0" rpy="0 0 0"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
        </inertial>
    </link>

    <joint name="joint_1" type="revolute">
        <parent link="base_link"/>
        <child link="first_link"/>
        <origin xyz="0 0 ${base_link_length/2}"/>
        <axis xyz="0 0 1"/>
        <limit lower="${limits_revolute_lower}" upper="${limits_revolute_upper}" effort="${limits_revolute_effort}" velocity="${limits_revolute_velocity}"/>
    </joint>

    <link name="first_link">
        <visual>
            <geometry>
                <cylinder radius="${first_link_radius}" length="${first_link_length}"/>
            </geometry>
            <origin xyz="0 0 ${first_link_length/2}" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${first_link_radius}" length="${first_link_length}"/>
            </geometry>
            <origin xyz="0 0 ${first_link_length/2}" rpy="0 0 0"/>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
        </inertial>
    </link>

    <joint name="joint_2" type="prismatic">
        <parent link="first_link"/>
        <child link="second_link"/>
        <origin xyz="0 0 ${first_link_length}"/>
        <axis xyz="0 1 0"/>
        <limit lower="${limits_prismatic_lower}" upper="${limits_prismatic_upper}" effort="${limits_prismatic_effort}" velocity="${limits_prismatic_velocity}"/>
    </joint>

    <link name="second_link">
        <visual>
            <geometry>
                <box size="${second_link_width} ${second_link_length} ${second_link_height}"/>
            </geometry>
            <origin xyz="0 0 ${second_link_height/2}" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${second_link_width} ${second_link_length} ${second_link_height}"/>
            </geometry>
            <origin xyz="0 0 ${second_link_height/2}" rpy="0 0 0"/>
        </collision>

        <inertial>
            <origin xyz="0 0 ${second_link_height/2}" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
        </inertial>
    </link>
</robot>
